# Generated by Django 4.2 on 2023-04-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='desired_price',
            field=models.FloatField(default=0),
        ),
    ]
