# Generated by Django 4.2 on 2023-04-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_items_itemstracked'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemstracked',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
